nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.0.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: 'E7A94808-3467-4150-B90D-EABDAEB9E0B4'
