import { GoogleAnalytics } from '@next/third-parties/google';

import { Providers } from '@/components/Providers';
import '@/styles/tailwind.css';
import '@/styles/fonts.css';
import 'focus-visible';

export const metadata = {
  metadataBase: new URL('https://rivet.gg')
};

export default function Layout({ children }) {
  return (
    <html lang='en'>
      <head>
        <GoogleAnalytics gaId='G-GHX1328ZFD' />

        {/* Generated by realfavicongenerator.net */}
        <link rel='apple-touch-icon' sizes='180x180' href='/icons/apple-touch-icon.png?v=3' />
        <link rel='icon' type='image/png' sizes='32x32' href='/icons/favicon-32x32.png?v=3' />
        <link rel='icon' type='image/png' sizes='16x16' href='/icons/favicon-16x16.png?v=3' />
        <link rel='manifest' href='/icons/site.webmanifest?v=3' />
        <link rel='mask-icon' href='/icons/safari-pinned-tab.svg?v=3' color='#151515' />
        <link rel='shortcut icon' href='/icons/favicon.ico?v=3' />
        <meta name='apple-mobile-web-app-title' content='Rivet' />
        <meta name='application-name' content='Rivet' />
        <meta name='msapplication-TileColor' content='#ffffff' />
        <meta name='msapplication-config' content='/icons/browserconfig.xml?v=3' />
        <meta name='theme-color' content='#ffffff' />
      </head>
      <body className='dark bg-charcole-950 antialiased'>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
