import Link from 'next/link';
import clsx from 'clsx';
import { Heading } from '@/components/Heading';
import { Tip, Info, Note } from '@/components/callouts';

export { ButtonGroup, Button } from '@/components/Button';
export { CodeGroup, Code as code, Pre as pre } from '@/components/Code';
export { ResourceGroup, Resource } from '@/components/Resources';
export { Snippet } from '@/components/Snippet';
export { Summary } from '@/components/Summary';
export { Accordion, AccordionGroup } from '@/components/Accordion';
export * from '@/components/callouts';
export { default as Image } from 'next/image';

export const a = Link;

export const h2 = function H2(props) {
  return <Heading level={2} {...props} />;
};

export const h3 = function H3(props) {
  return <Heading level={3} {...props} />;
};

export const table = function Table(props) {
  return (
    <div className='overflow-x-auto'>
      <table {...props} />
    </div>
  );
}

export function Tooltip({ tip, children }) {
  return (
    <span className='group relative z-10 inline'>
      <span className='underline decoration-zinc-400 decoration-dotted decoration-2 underline-offset-4 dark:decoration-zinc-500'>
        {children}
      </span>
      <span className='absolute bottom-full left-1/2 z-40 mb-0.5 hidden w-max max-w-[16rem] -translate-x-1/2 rounded-lg border border-gray-50 bg-black/50 px-1.5 py-1 pb-1 text-center text-xs text-gray-50 opacity-100 group-hover:flex dark:border-gray-500'>
        {tip}
      </span>
    </span>
  );
}

export function Row({ children }) {
  return (
    <div className='grid grid-cols-1 items-start gap-x-16 gap-y-10 xl:max-w-none xl:grid-cols-2'>
      {children}
    </div>
  );
}

export function Col({ children, sticky = false }) {
  return (
    <div className={clsx('[&>:first-child]:mt-0 [&>:last-child]:mb-0', sticky && 'xl:sticky xl:top-24')}>
      {children}
    </div>
  );
}

export function Properties({ children }) {
  return (
    <div className='my-6'>
      <ul
        role='list'
        className='m-0 max-w-[calc(theme(maxWidth.lg)-theme(spacing.8))] list-none divide-y divide-zinc-900/5 p-0 dark:divide-white/5'>
        {children}
      </ul>
    </div>
  );
}

export function Property({ name, type, children }) {
  return (
    <li className='m-0 px-0 py-4 first:pt-0 last:pb-0'>
      <dl className='m-0 flex flex-wrap items-center gap-x-3 gap-y-2'>
        <dt className='sr-only'>Name</dt>
        <dd>
          <code>{name}</code>
        </dd>
        <dt className='sr-only'>Type</dt>
        <dd className='font-mono text-xs text-zinc-400 dark:text-zinc-500'>{type}</dd>
        <dt className='sr-only'>Description</dt>
        <dd className='w-full flex-none [&>:first-child]:mt-0 [&>:last-child]:mb-0'>{children}</dd>
      </dl>
    </li>
  );
}

export function ComingSoon() {
  return <Info>🚧 This documentation page is coming soon 🚧</Info>;
}

export function WorkInProgress() {
  return <Info>🚧 This documentation page is a work in progress 🚧</Info>;
}

export function RequiresBetaSignup() {
  return (
    <Note>
      This guide requires access to the Rivet private beta. Request access{' '}
      <Link href='https://b8v8449klvp.typeform.com/rivet' target='_blank'>here</Link>.
    </Note>
  );
}

export function EnvTokenClient() {
  return (
    <Info>
      <p>In development, `RIVET_TOKEN` will use the development token generated by `rivet init`. In
      production, `RIVET_TOKEN` will be `undefined` and will use <Link href='/docs/general/concepts/tokenless-authentication-web'>tokenless
      authentication</Link>. This can be manually specified if you
      wish.</p>
      
      <p>More info:</p>

      <ul>
        <li><Link href='/docs/general/concepts/handling-game-tokens'>Handling game tokens</Link></li>
        <li><Link href='/docs/general/concepts/dev-tokens'>Development tokens</Link></li>
        <li><Link href='/docs/general/concepts/token-types#namespace-public'>Public tokens</Link></li>
      </ul>
    </Info>
  );
}

export function EnvTokenServer() {
  return (
    <Info>
      <p>
        In development, `RIVET_TOKEN` will use the development token generated by `rivet init`. In
        production, `RIVET_TOKEN` is automatically added to your environment by Rivet.
      </p>

      <p>More info:</p>

      <ul>
        <li>
          <Link href='/docs/general/concepts/handling-game-tokens'>Handling game tokens</Link>
        </li>
        <li>
          <Link href='/docs/general/concepts/dev-tokens'>Development tokens</Link>
        </li>
      </ul>
    </Info>
  );
}

export function ProtocolSupportMatrix() {
  return (
    <table>
      <tr>
        <th>Protocol</th>
        <th>
          <Link href='/docs/dynamic-servers/concepts/game-guard'>Rivet Game Guard</Link>
        </th>
        <th>
          <Link href='/docs/dynamic-servers/concepts/host-bridge-networking'>Host Network</Link>
        </th>
      </tr>
      <tr>
        <td></td>
        <td>
          <em>Requires single port</em>
        </td>
        <td>
          <em>Requires port range</em>
        </td>
      </tr>
      <tr>
        <td>HTTPS / Secure WebSocket</td>
        <td>✅</td>
        <td></td>
      </tr>
      <tr>
        <td>HTTP / WebSocket</td>
        <td>✅</td>
        <td></td>
      </tr>
      <tr>
        <td>TCP + TLS</td>
        <td>✅</td>
        <td></td>
      </tr>
      <tr>
        <td>TCP</td>
        <td>✅</td>
        <td>✅</td>
      </tr>
      <tr>
        <td>UDP / WebRTC / ENet / KCP</td>
        <td>✅</td>
        <td>✅</td>
      </tr>
    </table>
  );
}

export function InstallCli() {
  return (
    <Note>
      Make sure you have installed the Rivet CLI <Link href='https://github.com/rivet-gg/cli#installing' target='_blank'>here</Link>.
    </Note>
  );
}

export function CrashCourseUnrealBlueprint() {
  return null;
  return <Tip>
    <p>TODO: Unreal crash blueprints course</p>
    <ul>
      <li>Comments</li>
      <li>3 ways to create nodes</li>
    </ul>
  </Tip>
}

export function CrashCourseUnrealWidget() {
  return null;
  return <Tip>
    <p>TODO: Unreal crash blueprints course</p>
    <ul>
      <li>How to create a UI</li>
      <li>Common widget types</li>
    </ul>
  </Tip>
}